### ISSUE TITLE
error Converting *.tsv to *.trig

### ISSUE THREAD

**Issue by xristy** [buda-base/embedded-reader-import#6]
During:

    for i in input/*.tsv; do 
    b=`basename $i`; 
    bnoext=${b%.*}; 
    bfirst=${bnoext% *}; 
    python3 tsvtordf.py $i > output/$bfirst.trig; 
    done

The following error occurs

> Converting *.tsv to *.trig
Traceback (most recent call last):
  File "tsvtordf.py", line 169, in <module>
    dataset = linestordf(lines, graphnamefromfilepath(srcfile))
  File "tsvtordf.py", line 34, in linestordf
    i = addlineaschild(lines, i, None, g, None)
  File "tsvtordf.py", line 94, in addlineaschild
    return fillchildrenofline(lines, lineidx, thisres, g)
  File "tsvtordf.py", line 51, in fillchildrenofline
    thislineidx = addlineaschild(lines, thislineidx, lineres, g, partidx)
  File "tsvtordf.py", line 94, in addlineaschild
    return fillchildrenofline(lines, lineidx, thisres, g)
  File "tsvtordf.py", line 51, in fillchildrenofline
    thislineidx = addlineaschild(lines, thislineidx, lineres, g, partidx)
  File "tsvtordf.py", line 94, in addlineaschild
    return fillchildrenofline(lines, lineidx, thisres, g)
  File "tsvtordf.py", line 51, in fillchildrenofline
    thislineidx = addlineaschild(lines, thislineidx, lineres, g, partidx)
  File "tsvtordf.py", line 67, in addlineaschild
    cparts = splitcontent(line["content"])
  File "tsvtordf.py", line 111, in splitcontent
    rid = c[:openparidx]
UnboundLocalError: local variable 'openparidx' referenced before assignment

**Comment by eroux** [comment]
thanks! any idea what the file is? I'll debug it if you don't, no problem
