### ISSUE TITLE
error handling W1ERI0007

### ISSUE THREAD

**Issue by xristy** [buda-base/embedded-reader-import#9]
The conversion of the trig file to ttl format is failing because of a parse error where a Tibetan string is used where an integer is expected:

```
java -jar /home/admin/lib/rdf2rdf-1.0.1-2.3.1.jar output/W1ERI0007.trig tmp.ttl
converting output/W1ERI0007.trig to tmp.ttl (TriG to Turtle)
org.openrdf.rio.RDFParseException: '10)ཤེས་རབ་ཀྱི་ཕ་རོལ་དུ་ཕྱིན་པ་ཁམས་བརྒྱད་བསྡུད་པའི་དོན་གསལ་བར་བྱེད་པའི་འགྲེལ་བ་ལས་ཁམས་སྔ་མ་བཞི' is not a valid value for datatype http://www.w3.org/2001/XMLSchema#integer [line 578]
	at org.openrdf.rio.helpers.RDFParserBase.reportError(RDFParserBase.java:464)
	at org.openrdf.rio.turtle.TurtleParser.reportError(TurtleParser.java:1093)
	at org.openrdf.rio.helpers.RDFParserBase.createLiteral(RDFParserBase.java:344)
	at org.openrdf.rio.turtle.TurtleParser.parseQuotedLiteral(TurtleParser.java:597)
	at org.openrdf.rio.turtle.TurtleParser.parseValue(TurtleParser.java:535)
	at org.openrdf.rio.turtle.TurtleParser.parseObject(TurtleParser.java:411)
	at org.openrdf.rio.turtle.TurtleParser.parseObjectList(TurtleParser.java:337)
	at org.openrdf.rio.turtle.TurtleParser.parsePredicateObjectList(TurtleParser.java:330)
	at org.openrdf.rio.turtle.TurtleParser.parseImplicitBlank(TurtleParser.java:497)
	at org.openrdf.rio.turtle.TurtleParser.parseObject(TurtleParser.java:408)
	at org.openrdf.rio.turtle.TurtleParser.parseObjectList(TurtleParser.java:337)
	at org.openrdf.rio.turtle.TurtleParser.parsePredicateObjectList(TurtleParser.java:330)
	at org.openrdf.rio.turtle.TurtleParser.parseTriples(TurtleParser.java:299)
	at org.openrdf.rio.trig.TriGParser.parseGraph(TriGParser.java:142)
	at org.openrdf.rio.trig.TriGParser.parseStatement(TriGParser.java:89)
	at org.openrdf.rio.turtle.TurtleParser.parse(TurtleParser.java:184)
	at org.openrdf.rio.turtle.TurtleParser.parse(TurtleParser.java:129)
	at de.l3s.sesame2.tools.RDF2RDF.run(RDF2RDF.java:173)
	at de.l3s.sesame2.tools.RDF2RDF.main(RDF2RDF.java:35)
/home/admin/jena/bin/s-put -v http://172.31.59.129:13180/fuseki/bdrcrw http://purl.bdrc.io/graph/W1ERI0007.trig tmp.ttl
PUT http://172.31.59.129:13180/fuseki/bdrcrw http://purl.bdrc.io/graph/W1ERI0007.trig tmp.ttl
PUT http://172.31.59.129:13180/fuseki/bdrcrw?graph=http%3A%2F%2Fpurl.bdrc.io%2Fgraph%2FW1ERI0007.trig
  User-Agent:          SOH/Fuseki 1.0.0
  Content-Type:        text/turtle;charset=utf-8;charset=utf-8
  Content-Length:      32768
200 OK
  Fuseki-Request-Id:   11428
  Server:              Apache Jena Fuseki (3.13.0-SNAPSHOT)
  Content-Type:        application/json;charset=utf-8
  Transfer-Encoding:   chunked
  Date:                Wed, 02 Oct 2019 15:33:35 GMT
```

**Comment by xristy** [comment]
fixed somewhere along the line
